IF OBJECT_ID(N'dbo.CHRNAME', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CHRNAME
    (
        CHRNAM VARCHAR(4) NOT NULL
            CONSTRAINT PK_CHRNAME PRIMARY KEY,
        CHRDSC VARCHAR(10) NULL,
        FTIL DECIMAL(18, 4) NULL,
        FTOL DECIMAL(18, 4) NULL,
        CRDATE DATETIME NULL,
        [固定匯率] NUMERIC(18, 4) NULL,
        [鼎新] VARCHAR(10) NULL
    );
END;
GO

IF OBJECT_ID(N'dbo.[CHRNAME-HISTORY]', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.[CHRNAME-HISTORY]
    (
        CNO INT IDENTITY(1,1) NOT NULL,
        CHRNAM VARCHAR(4) NOT NULL,
        CHRDSC VARCHAR(10) NULL,
        FTIL DECIMAL(18, 4) NULL,
        FTOL DECIMAL(18, 4) NULL,
        CRDATE DATETIME NULL
    );
END;
GO
