IF OBJECT_ID(N'dbo.CHRNAME', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CHRNAME
    (
        CHRNAM NVARCHAR(10) NOT NULL
            CONSTRAINT PK_CHRNAME PRIMARY KEY,
        CHRDS NVARCHAR(20) NOT NULL,
        FTIL DECIMAL(18, 6) NULL,
        FTOL DECIMAL(18, 6) NULL,
        CRDATE DATETIME2(3) NULL
    );
END;
GO

IF OBJECT_ID(N'dbo.[CHRNAME-HISTORY]', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.[CHRNAME-HISTORY]
    (
        CHRNAM NVARCHAR(10) NOT NULL,
        FTIL DECIMAL(18, 6) NULL,
        FTOL DECIMAL(18, 6) NULL,
        CRDATE DATETIME2(3) NOT NULL
    );
END;
GO
